# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nikki Vinayan
title: Senior Software Engineer, Search
email: mail@nikvi dot com
website: www.nikvi.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: nikvi
github_username:  nikvi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: nikkivinayan
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Blog
  icon: fas fa-globe
  url: https://nikvi.dev
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/nikvi.jpg
about_content: | # this will include new lines to allow paragraphs


  I am most skilled in: <mark>search</mark> and <mark>data</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: GIPHY
        border: weak
        link: giphy.com
        link_text: GIPHY
        sub_title: Senior Software Engineer
        caption: October 2019 - Present
        quote: >
          GIPHY is the best way to search, share, discover and create GIFs on the Internet. 
        description: | # this will include new lines to allow paragraphs
          Giphy was aquired by Meta and later sold to Shutterstock. As a Search Engineer at GIPHY, I have contributed significantly to enhancing the search experience for a global audience through several key projects:
          * Development and Expansion of Trending Feed. I led the development of a dynamic trending feed that offers push-based recommendations, using robust data pipelines and Elastic MapReduce (EMR) to ensure real-time delivery. This feature has become a key product, enhancing user experience with personalized content.
          * User Search Enablement. I played a crucial role in enabling users to upload and search their content on GIPHY using their usernames, improving user interaction with the platform.
          * ML-Based Content Moderation Prototype. I collaborated on prototyping a machine learning-based content moderation system using Python, Seldon, Luigi, and Scikit. This project aimed to improve the platform's safety and inclusivity, ultimately being adopted by the content moderation team to enhance productivity and reduce exposure to harmful content.
      - layout: left
        title: Jet.com
        border: weak
        sub_title: Senior Software Engineer
        description:
          At Jet.com, which was acquired by Walmart, I focused on developing end-to-end solutions for search functionality. This included architecting solutions, ranking search results, creating analyst tools, managing search indexing, data pipelines, and deploying models. The main project involved building NLP libraries for Query Expansion and SKU understanding, which significantly improved search metrics by integrating machine learning into search service. Additionally, I was involved in various other responsibilities, such as
          * Use of A/B testing to assess the performance of models and algorithms at scale.
          * developed models and criteria for multi-dimensional analysis.
          * data pipelines to track customer interactions on Jet’s web and mobile platforms.
          * participated in an on-call rotation, handling deployment and load testing, using tools like Splunk and New Relic.
          * mentored new hires, conducted technical interviews
          * enabled CI/CD deployment pipelines, including migrating F# microservices to DotNetCore Docker services.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: left
      title: Stanford School of Engineering
      caption: 2021 -2022
      sub_title: Artificial Intelligence Professional Program
      link_text: https://online.stanford.edu/programs/artificial-intelligence-professional-program
      description:
        I completed three rigorous courses adapted from Stanford's on-campus graduate curriculum, covering topics such as AI principles and techniques, natural language processing with deep learning, and machine learning with graphs. These courses, taught by leading experts in the field, have equipped me with the knowledge and skills to tackle complex AI problems and implement cutting-edge algorithms effectively.


    - layout: left
      title: University of Melbourne
      caption: 2014 - 2015
      # link_text: sproogen/modern-resume-theme
      sub_title: MSc Computer Science
      description: | # this will include new lines to allow paragraphs
        The coursework comprised a blend of Distributed Systems and Declarative languages. Throughout my time there, I learned about Distributed Systems, Distributed Algorithms, Cluster, and Cloud Computing. My thesis focused on "Cache-based Path Routing in Roads."
        In my spare time, I served as a committee member of the Women in ICT club, where I held the position of President. Additionally, I served as the Computer Science Graduate Ambassador, facilitating "Introduction to Computing" sessions for high school girls and women. Concurrently, I volunteered with Robogals. Notably, I was selected as the International Grace Hopper Scholar in 2014 and was a finalist for the Google Anita Borg Scholarship the same year.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in search and software engineering some of my other interests and hobbies are:
      - Comic/Dark Fantasy geek esp:- Neil Gaiman,Terry Pratchett.
      - Giving back to the community through volunteering
      - Continous learning - NLP, AI, MLOps!

    # Look at this cool image  
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
