# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nikki Vinayan
title: Senior Software Engineer, Search
email: mail@nikvi dot com
website: www.nikvi.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: nikvi
github_username:  nikvi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: nikkivinayan
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Blog
  icon: fas fa-globe
  url: https://nikvi.dev
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/nikvi.jpg
about_content: | # this will include new lines to allow paragraphs


  I am most skilled in: <mark>search</mark> and <mark>data</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Melbourne
        caption: 2014 - 2015
        # link_text: sproogen/modern-resume-theme
        sub_title: MSc Computer Science
        quote: >
          Established in 1852, the University of Melbounrne is the second oldest higher education institution in the Australia, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just Australia but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at there, I learnt about Distributed Systems, Distributed Algorithms, Cluster and Cloud Computing. My thesis was "Cache based path routing in road."

          I spent a lot of my free time as a committee member of the *Women in ICT club* taking on the role of *President*. 
          I was also the *Computer Science Graduate Ambassador*, helped run "Introduction to Computing" sessions for high school girls and women. I also volunteered for *Robogals* aroud this time.
          Also International Grace Hopper Scholar in 2014, finalist for the Google Anita Borg Scholarship 2014.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: GIPHY
        link: giphy.com
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: October 2019 - Present
        quote: >
          GIPHY is the best way to search, share, discover and create GIFs on the Internet. 
        description: | # this will include new lines to allow paragraphs
            Design and code massively scalable services to provide a continually improving search experience, seen by millions of users around the globe daily. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in search and software engineering some of my other interests and hobbies are:
      - Comic/Dark Fantasy geek esp:- Neil Gaiman,Terry Pratchett.
      - Giving back to the community
      - Continous learning - NLP, AI, MLOps!

    # Look at this cool image  
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
